include_directories(${CMAKE_CURRENT_LIST_DIR})

if (NOT DEFINED XEXTRACTOR_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XExtractor/xextractor.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${XEXTRACTOR_SOURCES})
endif()
if (NOT DEFINED XDIALOGPROCESS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../FormatDialogs/xdialogprocess.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${XDIALOGPROCESS_SOURCES})
endif()
if (NOT DEFINED DIALOGDUMP_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../FormatDialogs/dialogdump.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${DIALOGDUMP_SOURCES})
endif()
if (NOT DEFINED XDIALOGPROCESS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../FormatDialogs/dialogdump.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${DIALOGDUMP_SOURCES} ${DIALOGDUMP_SOURCES})
endif()
if (NOT DEFINED XCOMBOBOXEX_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Controls/xcomboboxex.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${XCOMBOBOXEX_SOURCES})
endif()
if (NOT DEFINED XTABLEVIEW_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Controls/xtableview.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${XTABLEVIEW_SOURCES})
endif()
if (NOT DEFINED XOPTIONSWIDGET_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XOptions/xoptionswidget.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${XOPTIONSWIDGET_SOURCES})
endif()
if (NOT DEFINED XHEXVIEW_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XHexView/xhexview.cmake)
    set(XEXTRACTORWIDGET_SOURCES ${XEXTRACTORWIDGET_SOURCES} ${XHEXVIEW_SOURCES})
endif()

set(XEXTRACTORWIDGET_SOURCES
    ${XEXTRACTORWIDGET_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/xextractorwidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xextractorwidget.h
    ${CMAKE_CURRENT_LIST_DIR}/xextractorwidget.ui
    ${CMAKE_CURRENT_LIST_DIR}/dialogxextractor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dialogxextractor.h
    ${CMAKE_CURRENT_LIST_DIR}/dialogxextractor.ui
)
